// SPDX-FileCopyrightText: 2026 Ken Tobias
// SPDX-License-Identifier: GPL-3.0-or-later

//! Installing, removing and inspecting units — the half that touches the world.
//!
//! Unit *content* is generated by [`super::systemd`] as a pure function. This module only
//! decides where it goes and what `systemctl` is told about it, which keeps the part worth
//! golden-testing separate from the part that needs a filesystem.
//!
//! ## Writing is not activating
//!
//! [`write_units`] installs files and reloads the manager. It does **not** enable or start
//! anything. Activation is a separate, explicit call, because on this fleet the Go tool is
//! still the one actually taking backups — quietly adding a second hourly writer to a shared
//! repository is not something a command called `schedule` should do as a side effect.

use std::ffi::OsString;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::config::job::Job;
use crate::config::schedule::{Permission, Schedule};

use super::systemd::{self, UnitContext};

/// What an install did.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Installed {
    pub service: PathBuf,
    pub timer: PathBuf,
    /// Whether anything on disk actually changed.
    ///
    /// Re-running `schedule` with no config change should say so rather than implying work
    /// happened — and it means the command is safe to run repeatedly.
    pub changed: bool,
}

/// Write the units for `job`, creating the unit directory if needed.
///
/// Idempotent: identical content is not rewritten, so file timestamps stay meaningful.
pub fn write_units(
    job: &Job,
    schedule: &Schedule,
    ctx: &UnitContext,
    dir: &Path,
) -> io::Result<Installed> {
    fs::create_dir_all(dir)?;

    let service = dir.join(systemd::service_name(&job.name));
    let timer = dir.join(systemd::timer_name(&job.name));

    let a = write_if_changed(&service, &systemd::service_unit(job, schedule, ctx))?;
    let b = write_if_changed(&timer, &systemd::timer_unit(job, schedule))?;

    Ok(Installed {
        service,
        timer,
        changed: a || b,
    })
}

fn write_if_changed(path: &Path, contents: &str) -> io::Result<bool> {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == contents
    {
        return Ok(false);
    }
    fs::write(path, contents)?;
    Ok(true)
}

/// Remove the units for `job`. Returns the paths that existed and were deleted.
///
/// A unit that was not there is not an error: `unschedule` should be safe to run twice, and
/// on a host where the job was never scheduled.
pub fn remove_units(job_name: &str, dir: &Path) -> io::Result<Vec<PathBuf>> {
    let mut removed = Vec::new();
    for name in [
        systemd::service_name(job_name),
        systemd::timer_name(job_name),
    ] {
        let path = dir.join(name);
        match fs::remove_file(&path) {
            Ok(()) => removed.push(path),
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }
    }
    Ok(removed)
}

/// The `systemctl` argv for a permission scope.
///
/// Pure and separate from running it, so the `--user` decision is testable without a
/// service manager present.
pub fn systemctl_argv(permission: Permission, args: &[&str]) -> Vec<OsString> {
    let mut argv = vec![OsString::from("systemctl")];
    if permission == Permission::User {
        argv.push(OsString::from("--user"));
    }
    argv.extend(args.iter().map(OsString::from));
    argv
}

/// Run `systemctl` and return (success, trimmed stdout).
///
/// Stdout is captured because the query forms (`is-enabled`, `is-active`) answer through it
/// and exit non-zero for ordinary states — `is-enabled` on a disabled unit is a fact, not a
/// failure, so the exit code alone must not be read as an error.
pub fn systemctl(permission: Permission, args: &[&str]) -> io::Result<(bool, String)> {
    let argv = systemctl_argv(permission, args);
    let output = Command::new(&argv[0]).args(&argv[1..]).output()?;
    Ok((
        output.status.success(),
        String::from_utf8_lossy(&output.stdout).trim().to_string(),
    ))
}

/// Tell the service manager to re-read unit files.
pub fn daemon_reload(permission: Permission) -> io::Result<()> {
    systemctl(permission, &["daemon-reload"]).map(|_| ())
}

/// Enable and start a job's timer.
pub fn enable_timer(job_name: &str, permission: Permission) -> io::Result<(bool, String)> {
    systemctl(
        permission,
        &["enable", "--now", &systemd::timer_name(job_name)],
    )
}

/// Stop and disable a job's timer.
pub fn disable_timer(job_name: &str, permission: Permission) -> io::Result<(bool, String)> {
    systemctl(
        permission,
        &["disable", "--now", &systemd::timer_name(job_name)],
    )
}

/// What is installed and running for one job.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TimerStatus {
    pub job: String,
    pub units_present: bool,
    /// `None` when it could not be determined — an unreachable manager, say. Deliberately
    /// distinct from `Some(false)`: "not enabled" and "could not tell" are different
    /// answers and only one of them means the schedule is off.
    pub enabled: Option<bool>,
    pub active: Option<bool>,
    /// When the timer next fires, as systemd reports it.
    pub next_elapse: Option<String>,
}

/// Inspect one job's schedule.
pub fn timer_status(job: &Job, permission: Permission, dir: &Path) -> TimerStatus {
    let timer = dir.join(systemd::timer_name(&job.name));
    let units_present = timer.exists() && dir.join(systemd::service_name(&job.name)).exists();

    let unit = systemd::timer_name(&job.name);
    let enabled = systemctl(permission, &["is-enabled", &unit])
        .ok()
        .map(|(_, out)| out == "enabled");
    let active = systemctl(permission, &["is-active", &unit])
        .ok()
        .map(|(_, out)| out == "active" || out == "waiting");

    let next_elapse = systemctl(
        permission,
        &[
            "show",
            &unit,
            "--property=NextElapseUSecRealtime",
            "--value",
        ],
    )
    .ok()
    .map(|(_, out)| out)
    .filter(|s| !s.is_empty() && s != "n/a");

    TimerStatus {
        job: job.name.clone(),
        units_present,
        enabled,
        active,
        next_elapse,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::job::Operation;
    use crate::config::schedule::{At, Priority};

    fn job(name: &str) -> Job {
        Job {
            name: name.to_string(),
            profile: "p".to_string(),
            operations: vec![Operation::Backup],
            snapshot_sets: vec![],
            declared_snapshot_sets: 0,
            schedule: None,
            log: None,
        }
    }

    fn schedule() -> Schedule {
        Schedule {
            at: At::Hourly,
            permission: Permission::User,
            priority: Priority::Background,
        }
    }

    fn ctx() -> UnitContext<'static> {
        UnitContext {
            binary: Path::new("/usr/bin/rusticprofile"),
            config: Path::new("/etc/rp/jobs.yaml"),
            rustic_binary: Path::new("/usr/bin/rustic"),
        }
    }

    #[test]
    fn writing_creates_both_units_and_reports_a_change() {
        let dir = tempfile::tempdir().unwrap();
        let out = write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        assert!(out.changed);
        assert!(out.service.exists());
        assert!(out.timer.exists());
    }

    #[test]
    fn writing_the_same_content_twice_reports_no_change() {
        // `schedule` must be safe to re-run. Reporting a change when nothing changed would
        // make the command's output useless as a signal.
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        let second = write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        assert!(!second.changed);
    }

    #[test]
    fn changing_the_schedule_is_detected() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        let daily = Schedule {
            at: At::Daily,
            ..schedule()
        };
        assert!(
            write_units(&job("j"), &daily, &ctx(), dir.path())
                .unwrap()
                .changed
        );
    }

    #[test]
    fn writing_creates_a_missing_unit_directory() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("systemd/user");
        write_units(&job("j"), &schedule(), &ctx(), &nested).unwrap();
        assert!(nested.join("rusticprofile-j.timer").exists());
    }

    #[test]
    fn removing_reports_what_it_deleted_and_is_safe_to_repeat() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();

        let first = remove_units("j", dir.path()).unwrap();
        assert_eq!(first.len(), 2);

        // Running `unschedule` twice, or on a host where it was never scheduled, is not an
        // error — it is the desired end state either way.
        let second = remove_units("j", dir.path()).unwrap();
        assert!(second.is_empty());
    }

    #[test]
    fn removing_one_job_leaves_another_alone() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("keep"), &schedule(), &ctx(), dir.path()).unwrap();
        write_units(&job("drop"), &schedule(), &ctx(), dir.path()).unwrap();
        remove_units("drop", dir.path()).unwrap();
        assert!(dir.path().join("rusticprofile-keep.timer").exists());
        assert!(!dir.path().join("rusticprofile-drop.timer").exists());
    }

    #[test]
    fn user_scope_adds_the_user_flag_and_system_scope_does_not() {
        let u = systemctl_argv(Permission::User, &["daemon-reload"]);
        assert_eq!(
            u.iter()
                .map(|s| s.to_string_lossy().into_owned())
                .collect::<Vec<_>>(),
            vec!["systemctl", "--user", "daemon-reload"]
        );
        let s = systemctl_argv(Permission::System, &["daemon-reload"]);
        assert_eq!(
            s.iter()
                .map(|x| x.to_string_lossy().into_owned())
                .collect::<Vec<_>>(),
            vec!["systemctl", "daemon-reload"]
        );
    }

    #[test]
    fn status_reports_units_missing_without_consulting_anything_else() {
        let dir = tempfile::tempdir().unwrap();
        let st = timer_status(&job("never-scheduled"), Permission::User, dir.path());
        assert!(!st.units_present);
    }

    #[test]
    fn status_sees_units_once_they_are_written() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        assert!(timer_status(&job("j"), Permission::User, dir.path()).units_present);
    }
}
