// SPDX-FileCopyrightText: 2026 Ken Tobias
// SPDX-License-Identifier: GPL-3.0-or-later

//! Installing, removing and inspecting units — the half that touches the world.
//!
//! Unit *content* is generated by [`super::systemd`] as a pure function. This module only
//! decides where it goes and what `systemctl` is told about it, which keeps the part worth
//! golden-testing separate from the part that needs a filesystem.
//!
//! ## Writing is not activating
//!
//! [`write_units`] and [`write_agent`] install files and nothing more. Arming is a separate,
//! explicit call — [`enable_timer`] or [`bootstrap_agent`] — which is what lets `--write-only`
//! exist and what keeps a custom `--unit-dir` an inspection target rather than something a
//! service manager reads.
//!
//! ## Two backends, one shape
//!
//! systemd and launchd each get write / remove / inspect functions here. The asymmetry to
//! know about is that a systemd job is **two units** and a launchd job is **one agent**:
//! systemd cannot run a command from a timer, launchd can. Everything else — job gating, the
//! `at:` vocabulary, the spread window, the absolute-path requirement — is shared above this
//! module.

use std::ffi::OsString;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::config::job::Job;
use crate::config::schedule::{Permission, Schedule};

use super::UnitContext;
use super::calendar::Offset;
use super::{launchd, systemd};

/// What an install did.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Installed {
    pub service: PathBuf,
    pub timer: PathBuf,
    /// Whether anything on disk actually changed.
    ///
    /// Re-running `schedule` with no config change should say so rather than implying work
    /// happened — and it means the command is safe to run repeatedly.
    pub changed: bool,
}

/// Write the units for `job`, creating the unit directory if needed.
///
/// Idempotent: identical content is not rewritten, so file timestamps stay meaningful.
pub fn write_units(
    job: &Job,
    schedule: &Schedule,
    ctx: &UnitContext,
    dir: &Path,
) -> io::Result<Installed> {
    fs::create_dir_all(dir)?;

    let service = dir.join(systemd::service_name(&job.name));
    let timer = dir.join(systemd::timer_name(&job.name));

    let a = write_if_changed(&service, &systemd::service_unit(job, schedule, ctx))?;
    let b = write_if_changed(&timer, &systemd::timer_unit(job, schedule))?;

    Ok(Installed {
        service,
        timer,
        changed: a || b,
    })
}

fn write_if_changed(path: &Path, contents: &str) -> io::Result<bool> {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == contents
    {
        return Ok(false);
    }
    fs::write(path, contents)?;
    Ok(true)
}

/// Remove the units for `job`. Returns the paths that existed and were deleted.
///
/// A unit that was not there is not an error: `unschedule` should be safe to run twice, and
/// on a host where the job was never scheduled.
pub fn remove_units(job_name: &str, dir: &Path) -> io::Result<Vec<PathBuf>> {
    let mut removed = Vec::new();
    for name in [
        systemd::service_name(job_name),
        systemd::timer_name(job_name),
    ] {
        let path = dir.join(name);
        match fs::remove_file(&path) {
            Ok(()) => removed.push(path),
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }
    }
    Ok(removed)
}

/// The `systemctl` argv for a permission scope.
///
/// Pure and separate from running it, so the `--user` decision is testable without a
/// service manager present.
pub fn systemctl_argv(permission: Permission, args: &[&str]) -> Vec<OsString> {
    let mut argv = vec![OsString::from("systemctl")];
    if permission == Permission::User {
        argv.push(OsString::from("--user"));
    }
    argv.extend(args.iter().map(OsString::from));
    argv
}

/// Run `systemctl` and return (success, trimmed stdout).
///
/// Stdout is captured because the query forms (`is-enabled`, `is-active`) answer through it
/// and exit non-zero for ordinary states — `is-enabled` on a disabled unit is a fact, not a
/// failure, so the exit code alone must not be read as an error.
pub fn systemctl(permission: Permission, args: &[&str]) -> io::Result<(bool, String)> {
    let argv = systemctl_argv(permission, args);
    let output = Command::new(&argv[0]).args(&argv[1..]).output()?;
    Ok((
        output.status.success(),
        String::from_utf8_lossy(&output.stdout).trim().to_string(),
    ))
}

/// Tell the service manager to re-read unit files.
pub fn daemon_reload(permission: Permission) -> io::Result<()> {
    systemctl(permission, &["daemon-reload"]).map(|_| ())
}

/// Enable and start a job's timer.
pub fn enable_timer(job_name: &str, permission: Permission) -> io::Result<(bool, String)> {
    systemctl(
        permission,
        &["enable", "--now", &systemd::timer_name(job_name)],
    )
}

/// Stop and disable a job's timer.
pub fn disable_timer(job_name: &str, permission: Permission) -> io::Result<(bool, String)> {
    systemctl(
        permission,
        &["disable", "--now", &systemd::timer_name(job_name)],
    )
}

// ---------------------------------------------------------------------------------------
// launchd
//
// The same three jobs as above — write, remove, inspect — against `launchctl` instead of
// `systemctl`. Kept in this module for the same reason: content generation stays pure in
// `super::launchd`, and everything that touches the filesystem or a service manager lives
// here where it can be seen at a glance.
// ---------------------------------------------------------------------------------------

/// What installing a launchd agent did.
///
/// **One path, where systemd has two.** launchd puts the schedule and the program in one
/// job, so a scheduled job here is a single plist. Nothing is missing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InstalledAgent {
    pub plist: PathBuf,
    /// Whether anything on disk actually changed.
    pub changed: bool,
    /// The offset this job's runs land on, past its interval's base time.
    ///
    /// Reported so `schedule` can say *when* it will run — launchd cannot be asked, so the
    /// only place that answer exists is the plist that was just written.
    pub offset: Offset,
}

/// An arbitrary number for [`write_agent`] to spread a first install across its window.
///
/// **launchd has no `RandomizedDelaySec`**, so the spread has to be a real minute baked into
/// the plist, and something has to choose it. The requirement is *spread*, not
/// unpredictability: seven machines must not wake on the same instant, and nobody is trying to
/// guess when a backup runs.
///
/// `RandomState` is seeded by the operating system and re-keyed per call, which is exactly
/// enough for that and costs no dependency.
///
/// **It deliberately does not read the clock, and that is the whole point of this function
/// existing.** The first implementation took `Timestamp::now().subsec_nanosecond()` and
/// reduced it modulo the window — and on macOS the clock has *microsecond* resolution, so that
/// field is always a multiple of 1000. Since `1000 % 5 == 0`, every hourly job on every host
/// landed on minute 0: a spread that reported a spread and produced none. Measured, 10 samples
/// out of 10. A low-resolution clock is a bad source of arbitrariness whenever the consumer
/// reduces it modulo a small number, and the failure is invisible unless you look at the
/// value.
#[must_use]
pub fn arbitrary_offset_seed() -> u64 {
    use std::hash::{BuildHasher, RandomState};
    RandomState::new().hash_one(0u8)
}

/// Write the agent for `job`, creating the agent directory if needed.
///
/// **Idempotent, and that takes deliberate work here.** The fleet spread is chosen at
/// schedule time (launchd has no `RandomizedDelaySec`, so it has to be baked into the
/// calendar), which means a fresh choice on every run would rewrite an unchanged agent, move
/// the spread for no reason, and report `installed` every time — turning the `unchanged`
/// signal into noise.
///
/// So an offset already installed is **reused**: the plist is the record of what was chosen.
/// `arbitrary` is only consulted when there is nothing to reuse — a first install, or a plist
/// hand-edited into a shape [`super::launchd::installed_offset`] cannot read, in which case
/// the file legitimately changes.
pub fn write_agent(
    job: &Job,
    schedule: &Schedule,
    ctx: &UnitContext,
    dir: &Path,
    arbitrary: u64,
) -> io::Result<InstalledAgent> {
    fs::create_dir_all(dir)?;
    let plist = dir.join(launchd::plist_name(&job.name));

    let offset = fs::read_to_string(&plist)
        .ok()
        .and_then(|existing| launchd::installed_offset(&existing, schedule.at))
        .unwrap_or_else(|| Offset::within(schedule.at, arbitrary));

    let changed = write_if_changed(&plist, &launchd::agent_plist(job, schedule, offset, ctx))?;
    Ok(InstalledAgent {
        plist,
        changed,
        offset,
    })
}

/// Remove the agent for `job`. Returns the paths that existed and were deleted.
///
/// A plist that was not there is not an error, for the same reason as [`remove_units`]:
/// `unschedule` must be safe to repeat and safe on a host where the job was never scheduled.
pub fn remove_agent(job_name: &str, dir: &Path) -> io::Result<Vec<PathBuf>> {
    let path = dir.join(launchd::plist_name(job_name));
    match fs::remove_file(&path) {
        Ok(()) => Ok(vec![path]),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(Vec::new()),
        Err(e) => Err(e),
    }
}

/// The launchd domain a permission scope maps to.
///
/// `gui/<uid>` rather than `user/<uid>`: the GUI domain is the one a LaunchAgent belongs to,
/// and it is the domain that exists for a logged-in desktop user — which is also the reason
/// for [`super::launchd_login_caveat`].
///
/// The uid comes from `getuid()`, the same source the process itself would use, rather than
/// from `id -u`. Asking a different oracle than the code under test is the defect recorded in
/// `NOTES.md` v0.1.5, where a fixture shelled out to `hostname(1)` and disagreed with the
/// binary on every container.
#[must_use]
pub fn launchd_domain(permission: Permission) -> String {
    match permission {
        Permission::User => format!("gui/{}", current_uid()),
        Permission::System => "system".to_string(),
    }
}

/// This user's numeric id, for launchd's `gui/<uid>` domain.
///
/// **`0` off Unix, and that value can never be used.** `current_backend()` returns
/// [`Backend::Launchd`](super::Backend::Launchd) only on macOS, so every caller of
/// [`launchd_domain`] sits behind that match arm. The fallback exists so the launchd backend
/// keeps *compiling and being unit-tested* on every platform — the same reason
/// [`super::systemd::service_unit`] and [`super::launchd::agent_plist`] are pure functions
/// rather than `#[cfg]`-gated ones, and the reason `current_backend` is a runtime check at all.
///
/// A fabricated value that a caller *could* reach would be the thing this project refuses (see
/// `run::lock::budget`, which returns `None` rather than a plausible wait). This one is
/// unreachable by construction, which is a different case — but it is only worth the trade
/// because gating the alternative would fragment three `launchctl`-driving functions and the
/// `main.rs` dispatch arm that calls them.
fn current_uid() -> u32 {
    #[cfg(unix)]
    {
        nix::unistd::getuid().as_raw()
    }
    #[cfg(not(unix))]
    {
        0
    }
}

/// The `launchctl` argv for a domain-scoped subcommand.
///
/// Pure and separate from running it, so the domain decision is testable without launchd.
pub fn launchctl_argv(args: &[&str]) -> Vec<OsString> {
    let mut argv = vec![OsString::from("launchctl")];
    argv.extend(args.iter().map(OsString::from));
    argv
}

/// Run `launchctl` and return (success, trimmed stdout).
///
/// Stdout is captured for the same reason as [`systemctl`]: the query forms answer through it
/// and exit non-zero for ordinary states. `print` on an agent that is simply not loaded is a
/// fact, not a failure.
pub fn launchctl(args: &[&str]) -> io::Result<(bool, String)> {
    let argv = launchctl_argv(args);
    let output = Command::new(&argv[0]).args(&argv[1..]).output()?;
    Ok((
        output.status.success(),
        String::from_utf8_lossy(&output.stdout).trim().to_string(),
    ))
}

/// Load a job's agent and make sure launchd will actually run it.
///
/// Three steps, and each is there for a reason found by measurement:
///
/// 1. **`bootout` first, ignoring failure.** `bootstrap` fails outright when the service is
///    already loaded, so re-arming an existing agent needs the old one gone. Failure here is
///    the normal case on a first install and must not be reported.
/// 2. **`enable`.** `bootout`/`bootstrap` do not clear a persistent `launchctl disable`.
///    Without this, `schedule` on a job somebody once disabled would report success and
///    schedule nothing — a silent no-op wearing a success message.
/// 3. **`bootstrap`.** The modern replacement for `load`, and the step that actually
///    registers the calendar trigger.
pub fn bootstrap_agent(
    job_name: &str,
    permission: Permission,
    plist: &Path,
) -> io::Result<(bool, String)> {
    let domain = launchd_domain(permission);
    let service = format!("{domain}/{}", launchd::label(job_name));

    // Step 1: ignore the result — "not loaded" is the expected state on a first install.
    let _ = launchctl(&["bootout", &service]);
    // Step 2: clear any persistent disable, which bootstrap alone would not.
    let _ = launchctl(&["enable", &service]);
    // Step 3: the one whose result matters.
    launchctl(&["bootstrap", &domain, &plist.to_string_lossy()])
}

/// Unload a job's agent.
///
/// Not an error when the agent was never loaded — `unschedule` describes an end state, and
/// that end state is reached either way.
pub fn bootout_agent(job_name: &str, permission: Permission) -> io::Result<(bool, String)> {
    let service = format!(
        "{}/{}",
        launchd_domain(permission),
        launchd::label(job_name)
    );
    launchctl(&["bootout", &service])
}

/// Inspect one job's launchd agent, in the shape [`TimerStatus`] already describes.
///
/// **Deliberately reuses the systemd status type**, because it is what `status --json` emits
/// and a monitor written against one platform should not break on the other. The mapping:
///
/// | field | launchd meaning |
/// |---|---|
/// | `units_present` | the plist exists on disk |
/// | `enabled` | loaded into the domain **and** not persistently disabled |
/// | `active` | loaded — for a calendar job, launchd's resting state, the counterpart of a systemd timer being `waiting` |
/// | `next_elapse` | **always `None`** |
///
/// That last row is a measurement, not an omission: `launchctl print` reports the calendar
/// *descriptor* (`"Minute" => 22`) and never a next fire time. `None` already means "could
/// not tell" rather than `false` in this type and in the JSON, so the honest answer is
/// available — computing one ourselves and presenting it as launchd's would be inventing a
/// fact about a schedule, which is worse than admitting the gap.
pub fn agent_status(job: &Job, permission: Permission, dir: &Path) -> TimerStatus {
    let units_present = dir.join(launchd::plist_name(&job.name)).exists();

    let domain = launchd_domain(permission);
    let service = format!("{domain}/{}", launchd::label(&job.name));

    let loaded = launchctl(&["print", &service]).ok().map(|(ok, _)| ok);

    // A persistent `launchctl disable` survives bootout/bootstrap and suppresses the job, so
    // a loaded-but-disabled agent must not read as enabled.
    let label = launchd::label(&job.name);
    let disabled = launchctl(&["print-disabled", &domain])
        .ok()
        .map(|(_, out)| {
            out.lines()
                .filter(|line| line.contains(&format!("\"{label}\"")))
                .any(|line| line.contains("=> disabled") || line.contains("=> true"))
        })
        .unwrap_or(false);

    TimerStatus {
        job: job.name.clone(),
        units_present,
        enabled: loaded.map(|l| l && !disabled),
        active: loaded,
        next_elapse: None,
    }
}

/// What is installed and running for one job.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TimerStatus {
    pub job: String,
    pub units_present: bool,
    /// `None` when it could not be determined — an unreachable manager, say. Deliberately
    /// distinct from `Some(false)`: "not enabled" and "could not tell" are different
    /// answers and only one of them means the schedule is off.
    pub enabled: Option<bool>,
    pub active: Option<bool>,
    /// When the timer next fires, as systemd reports it.
    pub next_elapse: Option<String>,
}

/// Inspect one job's schedule.
pub fn timer_status(job: &Job, permission: Permission, dir: &Path) -> TimerStatus {
    let timer = dir.join(systemd::timer_name(&job.name));
    let units_present = timer.exists() && dir.join(systemd::service_name(&job.name)).exists();

    let unit = systemd::timer_name(&job.name);
    let enabled = systemctl(permission, &["is-enabled", &unit])
        .ok()
        .map(|(_, out)| out == "enabled");
    let active = systemctl(permission, &["is-active", &unit])
        .ok()
        .map(|(_, out)| out == "active" || out == "waiting");

    let next_elapse = systemctl(
        permission,
        &[
            "show",
            &unit,
            "--property=NextElapseUSecRealtime",
            "--value",
        ],
    )
    .ok()
    .map(|(_, out)| out)
    .filter(|s| !s.is_empty() && s != "n/a");

    TimerStatus {
        job: job.name.clone(),
        units_present,
        enabled,
        active,
        next_elapse,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::job::Operation;
    use crate::config::schedule::{At, Priority};

    fn job(name: &str) -> Job {
        Job {
            name: name.to_string(),
            profile: "p".to_string(),
            operations: vec![Operation::Backup],
            snapshot_sets: vec![],
            declared_snapshot_sets: 0,
            schedule: None,
            log: None,
        }
    }

    fn schedule() -> Schedule {
        Schedule {
            at: At::Hourly,
            permission: Permission::User,
            priority: Priority::Background,
        }
    }

    fn ctx() -> UnitContext<'static> {
        UnitContext {
            binary: Path::new("/usr/bin/rusticprofile"),
            config: Path::new("/etc/rp/jobs.yaml"),
            rustic_binary: Path::new("/usr/bin/rustic"),
        }
    }

    #[test]
    fn writing_creates_both_units_and_reports_a_change() {
        let dir = tempfile::tempdir().unwrap();
        let out = write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        assert!(out.changed);
        assert!(out.service.exists());
        assert!(out.timer.exists());
    }

    #[test]
    fn writing_the_same_content_twice_reports_no_change() {
        // `schedule` must be safe to re-run. Reporting a change when nothing changed would
        // make the command's output useless as a signal.
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        let second = write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        assert!(!second.changed);
    }

    #[test]
    fn changing_the_schedule_is_detected() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        let daily = Schedule {
            at: At::Daily,
            ..schedule()
        };
        assert!(
            write_units(&job("j"), &daily, &ctx(), dir.path())
                .unwrap()
                .changed
        );
    }

    #[test]
    fn writing_creates_a_missing_unit_directory() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("systemd/user");
        write_units(&job("j"), &schedule(), &ctx(), &nested).unwrap();
        assert!(nested.join("rusticprofile-j.timer").exists());
    }

    #[test]
    fn removing_reports_what_it_deleted_and_is_safe_to_repeat() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();

        let first = remove_units("j", dir.path()).unwrap();
        assert_eq!(first.len(), 2);

        // Running `unschedule` twice, or on a host where it was never scheduled, is not an
        // error — it is the desired end state either way.
        let second = remove_units("j", dir.path()).unwrap();
        assert!(second.is_empty());
    }

    #[test]
    fn removing_one_job_leaves_another_alone() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("keep"), &schedule(), &ctx(), dir.path()).unwrap();
        write_units(&job("drop"), &schedule(), &ctx(), dir.path()).unwrap();
        remove_units("drop", dir.path()).unwrap();
        assert!(dir.path().join("rusticprofile-keep.timer").exists());
        assert!(!dir.path().join("rusticprofile-drop.timer").exists());
    }

    #[test]
    fn user_scope_adds_the_user_flag_and_system_scope_does_not() {
        let u = systemctl_argv(Permission::User, &["daemon-reload"]);
        assert_eq!(
            u.iter()
                .map(|s| s.to_string_lossy().into_owned())
                .collect::<Vec<_>>(),
            vec!["systemctl", "--user", "daemon-reload"]
        );
        let s = systemctl_argv(Permission::System, &["daemon-reload"]);
        assert_eq!(
            s.iter()
                .map(|x| x.to_string_lossy().into_owned())
                .collect::<Vec<_>>(),
            vec!["systemctl", "daemon-reload"]
        );
    }

    #[test]
    fn status_reports_units_missing_without_consulting_anything_else() {
        let dir = tempfile::tempdir().unwrap();
        let st = timer_status(&job("never-scheduled"), Permission::User, dir.path());
        assert!(!st.units_present);
    }

    #[test]
    fn status_sees_units_once_they_are_written() {
        let dir = tempfile::tempdir().unwrap();
        write_units(&job("j"), &schedule(), &ctx(), dir.path()).unwrap();
        assert!(timer_status(&job("j"), Permission::User, dir.path()).units_present);
    }

    // ----------------------------------------------------------------------------------
    // launchd
    // ----------------------------------------------------------------------------------

    #[test]
    fn one_agent_is_written_where_systemd_needs_two_units() {
        let dir = tempfile::tempdir().unwrap();
        let out = write_agent(&job("j"), &schedule(), &ctx(), dir.path(), 7).unwrap();
        assert!(out.changed);
        assert!(out.plist.exists());
        assert_eq!(
            std::fs::read_dir(dir.path()).unwrap().count(),
            1,
            "a launchd job is one agent, not two files"
        );
    }

    #[test]
    fn rewriting_reuses_the_installed_offset_and_reports_no_change() {
        // The whole reason `write_agent` reads before it writes. The spread is chosen at
        // schedule time, so without reuse a second `schedule` would pick a different minute,
        // rewrite an unchanged agent and report `installed` — moving the fleet's spread for
        // no reason and making the `unchanged` signal meaningless.
        let dir = tempfile::tempdir().unwrap();
        let first = write_agent(&job("j"), &schedule(), &ctx(), dir.path(), 1).unwrap();
        let second = write_agent(&job("j"), &schedule(), &ctx(), dir.path(), 2).unwrap();
        assert!(
            !second.changed,
            "a different arbitrary number must not churn"
        );
        assert_eq!(first.offset, second.offset);
    }

    #[test]
    fn a_first_install_takes_the_offset_it_is_given() {
        let dir = tempfile::tempdir().unwrap();
        let out = write_agent(&job("j"), &schedule(), &ctx(), dir.path(), 3).unwrap();
        assert_eq!(out.offset, Offset::within(At::Hourly, 3));
    }

    #[test]
    fn changing_the_schedule_still_rewrites_the_agent() {
        // Reusing the offset must not turn into reusing the whole file: a job whose interval
        // changed has to be rewritten, or `schedule` silently keeps the old schedule.
        let dir = tempfile::tempdir().unwrap();
        write_agent(&job("j"), &schedule(), &ctx(), dir.path(), 1).unwrap();
        let daily = Schedule {
            at: At::Daily,
            ..schedule()
        };
        assert!(
            write_agent(&job("j"), &daily, &ctx(), dir.path(), 1)
                .unwrap()
                .changed
        );
    }

    #[test]
    fn removing_an_agent_reports_what_it_deleted_and_is_safe_to_repeat() {
        let dir = tempfile::tempdir().unwrap();
        write_agent(&job("j"), &schedule(), &ctx(), dir.path(), 1).unwrap();
        assert_eq!(remove_agent("j", dir.path()).unwrap().len(), 1);
        assert!(remove_agent("j", dir.path()).unwrap().is_empty());
    }

    #[test]
    fn removing_one_agent_leaves_another_alone() {
        let dir = tempfile::tempdir().unwrap();
        write_agent(&job("keep"), &schedule(), &ctx(), dir.path(), 1).unwrap();
        write_agent(&job("drop"), &schedule(), &ctx(), dir.path(), 1).unwrap();
        remove_agent("drop", dir.path()).unwrap();
        assert!(dir.path().join("local.rusticprofile.keep.plist").exists());
        assert!(!dir.path().join("local.rusticprofile.drop.plist").exists());
    }

    #[test]
    fn the_user_domain_is_the_gui_one_and_system_is_not_scoped_to_a_uid() {
        let user = launchd_domain(Permission::User);
        assert!(
            user.starts_with("gui/"),
            "a LaunchAgent belongs to the GUI domain: {user}"
        );
        assert_eq!(
            user,
            format!("gui/{}", current_uid()),
            "the uid must come from getuid(), not from a subprocess"
        );
        assert_eq!(launchd_domain(Permission::System), "system");
    }

    #[test]
    fn launchctl_argv_starts_with_the_binary_and_passes_arguments_through() {
        let argv: Vec<String> = launchctl_argv(&["bootout", "gui/501/x"])
            .iter()
            .map(|s| s.to_string_lossy().into_owned())
            .collect();
        assert_eq!(argv, vec!["launchctl", "bootout", "gui/501/x"]);
    }

    #[test]
    fn the_offset_seed_actually_spreads() {
        // A regression test for a bug found by *using* the feature, not by testing it. The
        // first implementation reduced the clock's nanosecond field modulo the window;
        // macOS's clock has microsecond resolution, so that field is always a multiple of
        // 1000, and 1000 % 5 == 0 — every host got minute 0, and `schedule` cheerfully
        // reported "hourly at 0 past" while spreading nothing. Measured 10/10.
        //
        // 200 samples over a 5-minute window: if the seed were degenerate this fails every
        // time, and if it is sound the chance of a single distinct value is 5 * (1/5)^200.
        let offsets: std::collections::HashSet<u8> = (0..200)
            .map(|_| Offset::within(At::Hourly, arbitrary_offset_seed()).minutes())
            .collect();
        assert!(
            offsets.len() > 1,
            "every seed folded to the same minute ({offsets:?}) — the fleet would not be spread"
        );
    }

    #[test]
    fn a_low_resolution_clock_would_still_degenerate_which_is_why_the_seed_is_not_one() {
        // Kept as the evidence for the choice above rather than as a check on `within`:
        // folding IS plain modulo, deliberately, because the reuse path needs a minute read
        // back out of a plist to come back unchanged. That is precisely why the *seed* must
        // not be a microsecond-resolution clock reading.
        for nanos in [976_122_000u64, 976_234_000, 123_456_000] {
            assert_eq!(
                Offset::within(At::Hourly, nanos).minutes(),
                0,
                "a multiple of 1000 folds to 0 in a 5-minute window"
            );
        }
    }

    #[test]
    fn agent_status_reports_a_missing_plist_without_consulting_launchd() {
        let dir = tempfile::tempdir().unwrap();
        let st = agent_status(&job("never-scheduled"), Permission::User, dir.path());
        assert!(!st.units_present);
    }

    #[test]
    fn agent_status_sees_the_plist_once_written_and_never_invents_a_next_run() {
        // launchd reports the calendar descriptor but no next fire time — measured against a
        // live agent. `None` means "could not tell" here and in the JSON, which is the honest
        // answer; computing one and presenting it as launchd's would be inventing a fact
        // about a schedule.
        let dir = tempfile::tempdir().unwrap();
        write_agent(&job("j"), &schedule(), &ctx(), dir.path(), 1).unwrap();
        let st = agent_status(&job("j"), Permission::User, dir.path());
        assert!(st.units_present);
        assert_eq!(st.next_elapse, None);
    }
}
