// SPDX-FileCopyrightText: 2026 Ken Tobias
// SPDX-License-Identifier: GPL-3.0-or-later

//! Generating systemd service and timer units.
//!
//! Everything here is a **pure function of (job, paths)**. Nothing is written, no unit is
//! installed and `systemctl` is not consulted — which is what makes the output
//! golden-testable and lets a unit be inspected before it exists anywhere.
//!
//! ## Two things the unit must not contain
//!
//! **A resolved date.** The config loader deliberately leaves `${date:…}` unresolved so
//! that a generated unit carries the *reference* rather than one day's value frozen at
//! install time — a unit written on the 1st would otherwise log to the 1st forever. The
//! simplest way to honour that is for the unit to carry no log path at all: the runner
//! resolves it per run. There is a test asserting no unit ever contains a date.
//!
//! **Scheduling priority applied in-process.** `Nice=` and `IOSchedulingClass=` belong in
//! the unit, which means no `nice`/`ionice` code is ever written in Rust. That is a
//! deliberate trade recorded in `PLAN.md` M2: systemd already does this correctly, per
//! cgroup, without privileges we would otherwise have to reason about.

use std::path::{Path, PathBuf};

use crate::config::job::Job;
use crate::config::schedule::{Permission, Priority, Schedule};

use super::UnitContext;
use super::calendar;

/// Where a unit is installed.
///
/// User units are the default and the fleet's normal case: backups run as the user whose
/// files they are, with that user's credentials and keyring. A system unit runs as root
/// and would need its own answer for both.
pub fn unit_dir(permission: Permission, home: &Path) -> PathBuf {
    match permission {
        Permission::User => home.join(".config/systemd/user"),
        Permission::System => PathBuf::from("/etc/systemd/system"),
    }
}

/// The service unit's file name for `job`.
pub fn service_name(job: &str) -> String {
    format!("rusticprofile-{job}.service")
}

/// The timer unit's file name for `job`.
pub fn timer_name(job: &str) -> String {
    format!("rusticprofile-{job}.timer")
}

/// The `[Service]` lines implementing a priority.
///
/// `Standard` emits nothing and inherits the manager's defaults, which is different from
/// emitting `Nice=0`: it leaves the choice with whoever configured the system.
fn priority_lines(priority: Priority) -> String {
    match priority {
        Priority::Background => "Nice=19\nIOSchedulingClass=idle\n".to_string(),
        Priority::Standard => String::new(),
    }
}

/// The service unit for `job`.
///
/// **Deliberately has no `[Install]` section.** systemd cannot run a command from a timer —
/// a `.timer` exists only to activate a `.service` — so every scheduled job is two units,
/// in this tool and in every other one. But only the *timer* should be enable-able. With an
/// `[Install]` section the service reports as `disabled` rather than `static`, which reads
/// as an invitation: `systemctl --user enable rusticprofile-<job>.service` would then run a
/// backup at every login, forever, with no timer involved and no schedule to explain it.
///
/// Without it systemd reports the service as `static` — activatable by its timer and by
/// nothing else — which is both true and the shape a reader expects.
pub fn service_unit(job: &Job, schedule: &Schedule, ctx: &UnitContext) -> String {
    format!(
        "# Generated by rusticprofile. Edits are lost on the next `schedule`.\n\
         [Unit]\n\
         Description=rusticprofile backup job {job_name}\n\
         Documentation=man:rusticprofile(1)\n\
         # Ordering against the network. NOTE: `network-online.target` does not exist in the\n\
         # *user* manager, so on `permission: user` these two lines are inert — measured,\n\
         # `PLAN.md` 5.11. They are kept because they are correct and load-bearing for a\n\
         # `permission: system` unit, where the target does exist. The user-timer case is\n\
         # covered by the retry on --background below, not by this ordering.\n\
         After=network-online.target\n\
         Wants=network-online.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         # --background marks the run as unattended, which enables the retry (PLAN.md 7.10,\n\
         # 7.12). It cannot be inferred from the environment: INVOCATION_ID and JOURNAL_STREAM\n\
         # are both set in an ordinary desktop terminal, so only an explicit flag put here by\n\
         # `schedule` can tell a scheduled run from a hand-typed one. On Unix the flag does not\n\
         # touch stdio, so rustic's diagnostics still reach the journal.\n\
         ExecStart={binary} run --name {job_name} --config {config} \
         --rustic-binary {rustic} --background\n\
         {priority}",
        job_name = job.name,
        binary = ctx.binary.display(),
        config = ctx.config.display(),
        rustic = ctx.rustic_binary.display(),
        priority = priority_lines(schedule.priority),
    )
}

/// The timer unit for `job`.
pub fn timer_unit(job: &Job, schedule: &Schedule) -> String {
    format!(
        "# Generated by rusticprofile. Edits are lost on the next `schedule`.\n\
         [Unit]\n\
         Description=rusticprofile backup timer {job_name}\n\
         Documentation=man:rusticprofile(1)\n\
         \n\
         [Timer]\n\
         OnCalendar={on_calendar}\n\
         # Laptops are asleep at 03:00. Without this a missed run is simply skipped, which\n\
         # for an intermittently-online fleet means the schedule quietly does nothing.\n\
         Persistent=true\n\
         # Seven machines share one repository; without a spread they would all wake on the\n\
         # same instant and contend for it.\n\
         RandomizedDelaySec={delay}\n\
         Unit={service}\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n",
        job_name = job.name,
        on_calendar = calendar::on_calendar(schedule.at),
        delay = calendar::randomized_delay_value(schedule.at),
        service = service_name(&job.name),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::job::Operation;
    use crate::config::schedule::At;

    fn job(name: &str) -> Job {
        Job {
            name: name.to_string(),
            profile: "p".to_string(),
            operations: vec![Operation::Backup, Operation::Forget],
            snapshot_sets: vec!["core".to_string()],
            declared_snapshot_sets: 1,
            schedule: None,
            log: Some("/var/log/rp/${date:%Y-%m-%d}.log".to_string()),
        }
    }

    fn schedule(at: At, priority: Priority) -> Schedule {
        Schedule {
            at,
            permission: Permission::User,
            priority,
        }
    }

    fn ctx() -> UnitContext<'static> {
        UnitContext {
            binary: Path::new("/usr/local/bin/rusticprofile"),
            config: Path::new("/home/u/.config/rusticprofile/jobs.yaml"),
            rustic_binary: Path::new("/home/u/.cargo/bin/rustic"),
        }
    }

    #[test]
    fn the_service_invokes_the_job_by_name_with_an_absolute_binary() {
        let s = service_unit(
            &job("dot-files"),
            &schedule(At::Hourly, Priority::Background),
            &ctx(),
        );
        assert!(s.contains("ExecStart=/usr/local/bin/rusticprofile run --name dot-files"));
        assert!(s.contains("--config /home/u/.config/rusticprofile/jobs.yaml"));
        assert!(s.contains("Type=oneshot"));
    }

    #[test]
    fn no_unit_ever_contains_a_date() {
        // The whole reason `${date:…}` is left unresolved at load time: a unit written
        // today must not log to today's file forever. The unit carries no log path at all,
        // so neither a resolved date nor a stray `${date:` can appear.
        for at in [At::Hourly, At::Daily, At::Weekly, At::Monthly] {
            let j = job("dot-files");
            let sch = schedule(at, Priority::Background);
            for unit in [service_unit(&j, &sch, &ctx()), timer_unit(&j, &sch)] {
                assert!(
                    !unit.contains("${date:"),
                    "unresolved date leaked into a unit"
                );
                assert!(!unit.contains("2026"), "a literal year leaked into a unit");
                assert!(!unit.contains(".log"), "a log path leaked into a unit");
            }
        }
    }

    #[test]
    fn background_priority_lands_in_the_unit_not_in_process() {
        let bg = service_unit(
            &job("j"),
            &schedule(At::Daily, Priority::Background),
            &ctx(),
        );
        assert!(bg.contains("Nice=19"));
        assert!(bg.contains("IOSchedulingClass=idle"));
    }

    #[test]
    fn standard_priority_emits_nothing_rather_than_nice_zero() {
        // Emitting Nice=0 would override a deliberate system-wide default; emitting
        // nothing leaves that choice where it belongs.
        let std = service_unit(&job("j"), &schedule(At::Daily, Priority::Standard), &ctx());
        assert!(!std.contains("Nice="));
        assert!(!std.contains("IOSchedulingClass="));
    }

    #[test]
    fn the_timer_waits_for_the_network_and_survives_a_sleeping_laptop() {
        let t = timer_unit(&job("j"), &schedule(At::Daily, Priority::Background));
        assert!(t.contains("Persistent=true"), "a missed run must catch up");
        assert!(
            t.contains("RandomizedDelaySec="),
            "the fleet must be spread"
        );
        let s = service_unit(
            &job("j"),
            &schedule(At::Daily, Priority::Background),
            &ctx(),
        );
        assert!(s.contains("After=network-online.target"));
    }

    #[test]
    fn the_unit_names_rustic_by_absolute_path() {
        // The unit must not depend on the service manager's PATH. With linger the user
        // manager starts at boot with /usr/local/bin:/usr/bin — no login shell, so no
        // ~/.cargo/bin — and a bare `rustic` is then unresolvable at 03:00 with nobody
        // watching. Measured on a real host: every run failed with
        // `could not run rustic: No such file or directory`, on a unit byte-identical to
        // one that worked elsewhere.
        let unit = service_unit(
            &job("dot-files"),
            &schedule(At::Hourly, Priority::Background),
            &ctx(),
        );
        assert!(
            unit.contains("--rustic-binary /home/u/.cargo/bin/rustic"),
            "{unit}"
        );
    }

    #[test]
    fn the_unit_marks_the_run_as_unattended_so_the_retry_applies() {
        // `PLAN.md` 5.11/7.12. A `Persistent=true` catch-up fires within milliseconds of the
        // timer starting — measured, and `RandomizedDelaySec` does not delay it even at 3600s
        // — so on a laptop the run replacing a missed hour lands seconds after a resume,
        // before the network is up. Measured on a real host: a catch-up fired in the same
        // second as `PM: suspend exit` and died on DNS, while the network became usable 11
        // seconds later, so a retry two minutes out would have succeeded.
        //
        // The flag is the whole gate, and it has to be one: `INVOCATION_ID` and
        // `JOURNAL_STREAM` are both set in an ordinary desktop terminal, so no environment
        // check can tell a scheduled run from a hand-typed one. Dropping `--background` here
        // silently removes the retry from every Linux host.
        for at in [At::Hourly, At::Daily, At::Weekly, At::Monthly] {
            for priority in [Priority::Standard, Priority::Background] {
                let unit = service_unit(&job("dot-files"), &schedule(at, priority), &ctx());
                let exec = unit
                    .lines()
                    .find(|l| l.starts_with("ExecStart="))
                    .expect("ExecStart");
                assert!(
                    exec.split_whitespace().any(|t| t == "--background"),
                    "no --background for {at:?}/{priority:?}: {exec}"
                );
            }
        }
    }

    #[test]
    fn the_network_ordering_is_documented_as_inert_for_a_user_unit() {
        // The directives stay because they are correct for a `permission: system` unit, where
        // `network-online.target` exists. They are inert for a user timer — measured,
        // `LoadState=not-found` — and a comment claiming a protection that is not there is
        // exactly the failure this project exists to refuse, so the unit must say so.
        let unit = service_unit(
            &job("dot-files"),
            &schedule(At::Hourly, Priority::Background),
            &ctx(),
        );
        assert!(unit.contains("After=network-online.target"), "{unit}");
        assert!(
            unit.contains("does not exist in the"),
            "the inert-on-user-manager caveat is missing: {unit}"
        );
    }

    #[test]
    fn every_path_in_the_unit_is_absolute() {
        // Three paths, one rule: nothing in a unit may be resolved against an environment
        // the unit does not control.
        let unit = service_unit(
            &job("dot-files"),
            &schedule(At::Hourly, Priority::Background),
            &ctx(),
        );
        let exec = unit
            .lines()
            .find(|l| l.starts_with("ExecStart="))
            .expect("ExecStart");
        for token in exec.trim_start_matches("ExecStart=").split_whitespace() {
            // Flags, the subcommand and the job name are not paths; anything that looks
            // like one must be rooted.
            if token.contains('/') {
                assert!(
                    token.starts_with('/'),
                    "relative path in unit: {token}\n{exec}"
                );
            }
        }
    }

    #[test]
    fn the_service_has_no_install_section() {
        // Only the timer is enable-able. With an `[Install]` section systemd reports the
        // service as `disabled` rather than `static`, which reads as an invitation —
        // `systemctl --user enable <job>.service` would then run a backup at every login,
        // forever, with no timer and nothing to explain it.
        let unit = service_unit(
            &job("j"),
            &schedule(At::Hourly, Priority::Background),
            &ctx(),
        );
        assert!(!unit.contains("[Install]"), "{unit}");
        assert!(!unit.contains("WantedBy"), "{unit}");
    }

    #[test]
    fn only_the_timer_declares_where_it_installs() {
        let timer = timer_unit(&job("j"), &schedule(At::Hourly, Priority::Background));
        assert!(timer.contains("[Install]"));
        assert!(timer.contains("WantedBy=timers.target"));
    }

    #[test]
    fn the_timer_points_at_its_own_service() {
        let t = timer_unit(
            &job("dot-files"),
            &schedule(At::Hourly, Priority::Background),
        );
        assert!(t.contains("Unit=rusticprofile-dot-files.service"));
        assert!(t.contains("OnCalendar=hourly"));
    }

    #[test]
    fn unit_names_are_namespaced_so_they_cannot_collide_with_anything_else() {
        assert_eq!(service_name("dot-files"), "rusticprofile-dot-files.service");
        assert_eq!(timer_name("dot-files"), "rusticprofile-dot-files.timer");
    }

    #[test]
    fn user_and_system_units_go_to_different_directories() {
        let home = Path::new("/home/u");
        assert_eq!(
            unit_dir(Permission::User, home),
            PathBuf::from("/home/u/.config/systemd/user")
        );
        assert_eq!(
            unit_dir(Permission::System, home),
            PathBuf::from("/etc/systemd/system")
        );
    }

    #[test]
    fn generation_is_pure() {
        // No clock, no environment, no filesystem: the same inputs must always give the
        // same unit, or golden tests mean nothing and a re-`schedule` would churn.
        let j = job("dot-files");
        let s = schedule(At::Hourly, Priority::Background);
        assert_eq!(service_unit(&j, &s, &ctx()), service_unit(&j, &s, &ctx()));
        assert_eq!(timer_unit(&j, &s), timer_unit(&j, &s));
    }
}
